image:
  name: eu.gcr.io/savannah-emr/fls-image:15-02-21

stages:
  - test

SILContactsTests:
  stage: test
  timeout: 10 minutes
  tags:
    - healthcloud-multi
  script:
    - flutter pub get
    - flutter analyze
    - flutter test --coverage test
    - genhtml -q -o coverage coverage/lcov.info
    - python3 check_coverage.py 0.00
