name: sil_user_profile
description: A new Flutter package project.
version: 0.0.1
publish_to: none
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^2.0.0-nullsafety.0
  built_collection: ^5.0.0
  built_value: ^8.0.2
  # async_redux: ^9.0.0
  async_redux:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/async_redux_flutter.git
      ref: 0.0.2
  sil_themes:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_themes.git
      ref: 0.0.3-nullsafety
  sil_ui_components:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_ui_components.git
      ref: 0.0.10-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0


flutter:
