name: user_profile
description: A shared library that is responsible for the user profile displayed on both apps.
version: 0.1.11-nullsafety
homepage: https://github.com/savannahghi/user_profile
repository: https://github.com/savannahghi/user_profile
issue_tracker: https://github.com/savannahghi/user_profile/issues
documentation: https://github.com/savannahghi/user_profile/doc

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  app_wrapper: ^0.1.1 # internal (formerly sil_app_wrapper)
  async_redux: ^10.0.1
  debug_logger: ^0.0.21
  domain_objects: ^0.0.19-nullsafety # internal (formerly sil_core_domain_objects)
  dotted_border: ^2.0.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_graphql_client: ^0.1.1 # internal (formerly sil_graphql_client)
  http: ^0.13.3
  material_design_icons_flutter: ^5.0.5955-rc.1
  rxdart: ^0.27.0
  shared_themes: ^0.0.9 # internal (formerly sil_themes)
  shared_ui_components: ^0.1.23-nullsafety # internal (formerly sil_ui_components)
  webview_flutter: ^2.0.2 # embedded webView

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.10

flutter:
  uses-material-design: true
  assets:
    - packages/shared_ui_components/assets/ke.png
    - packages/shared_ui_components/assets/try_features.jpg
    - packages/shared_ui_components/assets/tz.png
    - packages/shared_ui_components/assets/ug.png
    - packages/shared_ui_components/assets/us.png
