name: sil_user_profile
description: A new Flutter package project.
version: 0.0.1
publish_to: none
author:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  async_redux: ^10.0.1
  debug_logger: ^0.0.21
  domain_objects: ^0.0.18-nullsafety
  dotted_border: ^2.0.0-nullsafety.0
  flutter:
    sdk: flutter
  http: ^0.13.0
  rxdart: ^0.27.0

  sil_app_wrapper:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_app_wrapper.git
      ref: 0.0.13

  sil_graphql_client:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_graphql_client.git
      ref: 0.1.01

  sil_themes:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_themes.git
      ref: 0.1.00

  sil_ui_components:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_ui_components.git
      ref: 0.1.23

  webview_flutter: ^2.0.2 #embedded webView

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.10

flutter:
  uses-material-design: true
  assets:
    - packages/sil_ui_components/assets/ke.png
    - packages/sil_ui_components/assets/try_features.jpg
    - packages/sil_ui_components/assets/tz.png
    - packages/sil_ui_components/assets/ug.png
    - packages/sil_ui_components/assets/us.png
