name: user_profile
description: A shared library that is responsible for the user profile displayed on both apps.
version: 0.2.3
homepage: https://github.com/savannahghi/user_profile
repository: https://github.com/savannahghi/user_profile
issue_tracker: https://github.com/savannahghi/user_profile/issues
documentation: https://github.com/savannahghi/user_profile/blob/main/doc/readme.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  app_wrapper: ^0.2.1
  async_redux: ^16.0.0
  debug_logger: ^0.0.23
  domain_objects: ^0.2.2
  dotted_border: ^2.0.0+2
  flutter:
    sdk: flutter
  flutter_graphql_client: ^0.2.0
  http: ^0.13.5
  material_design_icons_flutter: ^5.0.6996
  rxdart: ^0.27.5
  shared_themes: ^0.2.0
  shared_ui_components: ^0.2.4
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.10

flutter:
  uses-material-design: true
  assets:
    - packages/shared_ui_components/assets/ken.png
    - packages/shared_ui_components/assets/try_features.jpg
    - packages/shared_ui_components/assets/tza.png
    - packages/shared_ui_components/assets/uga.png
    - packages/shared_ui_components/assets/usa.png
